---
output:
  html_document: default
  pdf_document: default
---
```{r}
# Load required libraries
library(dplyr)
library(stringr)
library(readr)
```
## 2. Data Loading
```{r}
# Load raw dataset
data_raw <- read_tsv("~/Downloads/GitHub/DS2023_Data_Programming_R_Coursework/data/raw/msk_chord_2024_clinical_data.tsv")

# Inspect structure
glimpse(data_raw)
```
## 3. Handling Missing Values
```{r}
colnames(data_raw)
```

```{r}
library(janitor)
data_raw <- clean_names(data_raw)
data_clean <- data_raw %>% filter(!is.na(somatic_status))
```
```{r}
data_clean <- data_clean %>%
  select(
    somatic_status,
    current_age,
    sex,
    cancer_type,
    stage_highest_recorded
  )
```
```{r}
glimpse(data_clean)
```
## 4. Age
```{r}
summary(data_clean$current_age)
data_clean <- data_clean %>%
  filter(!is.na(current_age))
```
## 5. Gender
```{r}
data_clean <- data_clean %>%
  mutate(
    sex = str_to_lower(sex),
    sex = str_trim(sex),
    sex = case_when(
      sex %in% c("m", "male") ~ "Male",
      sex %in% c("f", "female") ~ "Female",
      TRUE ~ NA_character_
    )
  ) %>%
  filter(!is.na(sex))
```

## 6. Stages
```{r}
data_clean <- data_clean %>%
  mutate(
    stage_highest_recorded = str_to_lower(stage_highest_recorded),
    stage_highest_recorded = case_when(
      str_detect(stage_highest_recorded, "1-3") ~ "Stage I–III",
      str_detect(stage_highest_recorded, "4") ~ "Stage IV",
      TRUE ~ NA_character_
    )
  ) %>%
  filter(!is.na(stage_highest_recorded))
```

## 7. Factors convert
```{r}
data_clean <- data_clean %>%
  mutate(
    somatic_status = factor(somatic_status),
    sex = factor(sex),
    cancer_type = factor(cancer_type),
    stage_highest_recorded = factor(stage_highest_recorded)
  )

str(data_clean)
```
## 8. Final missing values check
```{r}
colSums(is.na(data_clean))
```

```{r}
getwd()
```

```{r}
# Save cleaned dataset
write.csv(
  data_clean,
  file = "data/clean_data.csv",
  row.names = FALSE
)
```










































